export const departments = [
  "Accounting",
  "Bangla",
  "Botany",
  "Chemistry",
  "Economics",
  "English",
  "Finance & Banking",
  "History",
  "Islamic History & Culture",
  "Arabic & Islamic Studies",
  "Management",
  "Marketing",
  "Mathematics",
  "Philosophy",
  "Physics",
  "Political Science",
  "Social Work",
  "Sociology",
  "Statistics",
  "Zoology",
];

export const governmentDesignations = [
  "Principal",
  "Vice Principal",
  "Professor",
  "Associate Professor",
  "Assistant Professor",
  "Lecture",
  "Physical Teacher",
  "Librarian",
  "Demonstrator",
  "Head Assistant",
  "Accountant",
  "Assistant Accountant",
  "Store Keeper",
  "Cashier",
  "Office Assistant Cum-Computer Operator",
  "Book Sorter",
  "Skill Bearer",
  "Office Assistant",
];
